server {
    listen 3000;
    
    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        # This try_files directive is required for SPA routing to work correctly
        try_files $uri $uri/ /index.html;
    }
}
