server {
    listen 8080;

    # Route /api/projects to the NestJS Backend
    location /api/projects/ {
        proxy_pass http://host.docker.internal:4000/;
        proxy_set_header Host $host;
    }

    # Route /api/estimation to the Python FastAPI Backend
    location /api/estimation/ {
        proxy_pass http://host.docker.internal:8000/;
        proxy_set_header Host $host;
    }

    # Route everything else to the React Frontend
    location / {
        proxy_pass http://host.docker.internal:3000/;
        proxy_set_header Host $host;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }
}
